version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet publish -o publish
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   kinvitech/kinvitechcicd:$TAG
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push kinvitech/kinvitechcicd:$TAG
