version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: dotnet restore /src/HelloCircleCI/HelloCircleCI.csproj
      - run: dotnet build
      - run: dotnet publish -o publish
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          TAG=kinvitechcircleciimage.0.1.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t kinvitech/kinvitechcicd:$TAG .
          docker push kinvitech/kinvitechcicd:$TAG
